Metrics/LineLength:
  Max: 100

Style/NumericLiteralPrefix:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'spec/classes/stub_spec.rb'

Metrics/BlockLength:
  Max: 428

Security/YAMLLoad:
  Exclude:
    - 'bin/stub'
